// src/components/JobsFilter.vue
<template>
  <div id="jobsLayout">
    <div id="filter">
      <form>
        <div class="section">
          Type
        </div>
        <input
          name="fullTime"
          type="checkbox"
          v-model="filter.fullTime"
        >
        <label for="fullTime"> Full-time</label><br/>

        <div class="section">
          Open Source
        </div>
        <select
          name="ossTimeGt"
          v-model.number="filter.ossTimeGt"
          >
          <option value="0"></option>
          <option value="25">&gt; 25%</option>
          <option value="50">&gt; 50%</option>
          <option value="75">&gt; 75%</option>
          <option value="100">100%</option>
        </select>
        <label for="ossTimeGt"> OSS time</label>

        <button class="reset" type="reset" @click="resetFilter">Reset</button>
      </form>
    </div>
    <Jobs :jobs="filteredJobs"/>
  </div>
</template>

<script>
  import Jobs from './Jobs.vue'

  import jobData from '../jobs.js'
  import filterJobs, { defaultFilter } from '../filter-jobs.js';
  import marked from 'marked'
  import DOMPurify from 'dompurify'

  const jobsWithMarkdown = jobData.map((job) => ({
    ...job,
    description: DOMPurify.sanitize(
      marked(job.description),
      {ALLOWED_TAGS: ['em', 'strong', 'ul', 'li', 'br', 'p']}
    )
  }))

  export default {
    name: 'JobsFilter',
    components: {
      Jobs
    },
    data: () => ({
      filter: defaultFilter()
    }),
    methods: {
      resetFilter() {
        this.filter = defaultFilter()
        console.log(this.filter)
      }
    },
    computed: {
      filteredJobs() {
        return filterJobs(jobsWithMarkdown, this.filter)
      }
    },
  }
</script>

<style>
#jobsLayout {
  display: flex;
}
#filter {
  width: 10%;
  background: #eee;
  padding: 2rem;
}
.section {
  font-weight: bold;
  margin-bottom: 0.5rem;
  padding-top: 1rem;
}
.reset {
  margin-top: 2rem;
  background: gray;
  color: white;
  border: 0;
  padding: 0.5rem 1rem 0.5rem 1rem;
}
</style>

// src/components/JobsFilter.jsx
import React from "react";

import { useForm } from "react-hook-form";

import Jobs from "./Jobs";
import HowToPost from "./HowToPost";

import jobData from '../jobs.js';
import filterJobs from '../filter-jobs.js';
import jobToMarkdown from '../jobToMarkdown.js';


const defaultFormValues = {
  fullTime: false,
  ossTimeGt: 0
};

const JobsFilter = () => {
  const { register, watch, reset } = useForm();
  const formData = watch();

  const jobsWithMarkdown = jobData.map(jobToMarkdown);

  const jobs = filterJobs(jobsWithMarkdown, formData);

  return (
    <div className="jobsLayout">
      <div className="leftColumn">
        <div className="filter">
          <form>
            <div className="section">
              Type
            </div>

            <label>
              <input name="fullTime" type="checkbox" ref={register} />
              Full-time
            </label>

            <div className="section">
              Open Source
            </div>

            <label>
              <select name="ossTimeGt" ref={register}>
                <option value="0">Any</option>
                <option value="25">&gt; 25%</option>
                <option value="50">&gt; 50%</option>
                <option value="75">&gt; 75%</option>
                <option value="100">100%</option>
              </select>
              &nbsp;OSS time
            </label>

            <div className="section">
              Location
            </div>
            <label>
              <input name="remote" type="checkbox" ref={register} />
              Remote
            </label>

            <button
              type="button"
              className="reset"
              onClick={() => reset(defaultFormValues)}
            >
              Reset
            </button>
          </form>
        </div>
        <HowToPost/>
      </div>
      <Jobs jobs={jobs}/>
    </div>
  )
};


export default JobsFilter;
